env:
    SEED: 42
    CUDA_DEVICE_ORDER: "PCI_BUS_ID"
    OMP_NUM_THREADS: "4"
    # TRANSFORMERS_CACHE: /home/data/hf_cache/
paths:
    data_dir: "data/"
    log_dir: "artifacts/logs/"
    checkpoint_dir: "artifacts/checkpoints/"
    results_dir: "artifacts/results/"
model:
    # path: google/gemma-3-4b-it
    # path: NousResearch/Llama-2-7b-chat-hf
    path: /workspace/kazistova/models/qwen
    # path: /workspace/kazistova/models/Llama-3.1-8B-Instruct
    seqlen: 2048
benchmarks:
    ppl_wikitext2:
        run_ppl: True
        batch_size: 1
    harness:
        run_lm_eval: True
        tasks:
            # [
            #     "boolq"
            # ]
            [
                "boolq",
                "winogrande",
                "piqa",
                "arc_easy"
                # "arc_challenge",
                # "hellaswag",
                # "openbookqa",
                # "rte",
                # "mmlu",
                # "lambada_standard",
                # "lambada_openai"
            ]
        num_fewshot: 0
        batch_size: 1024
        apply_chat_template: False # for instructive models run with True and False
pruning:
    sparsity_type: semi-structured_act_magnitude # unstructured_act_magnitude, unstructured_weight_magnitude, semi-structured_act_magnitude, semi_structural_L_pruner
    transformation_type: learnable  # none learnable
    # sparsity_ratio: 0.2 # for unstructured pruning
    additional_transformation: null
    prune_n: 8
    prune_m: 16
    module: layers #layers mlp_blocks attn_blocks
    target_modules:
        [
            # "q_proj",
            # "k_proj",
            # "v_proj",
            "o_proj",
            "gate_proj",
            "up_proj",
            "down_proj"
        ]
        # [
        #     "k_proj",
        #     "v_proj",
        #     "gate_proj",
        #     "down_proj",
        # ]

finetuning:
    output_dir: /workspace/kazistova/LLM_activation_pruning/act_prune/artifacts/models/llama3_1_8b_wiki
    dataset_name: Salesforce/wikitext
    dataset_config_name: wikitext-2-raw-v1
    type: "global"
    parameters: "r-sparce"
    seed: 11
    max_seq_length: 2048
    preprocessing_num_workers: 8
    trust_remote_code: True
    num_train_epochs: 1
    # max_steps: 1000
    learning_rate: !!float 1e-4
    weight_decay: 0.0
    lr_scheduler_type: linear
    warmup_ratio:  0.03
    per_device_train_batch_size: 1
    per_device_eval_batch_size: 1
    gradient_accumulation_steps: 16
    gradient_checkpointing: False
    save_strategy: steps
    save_steps: 200
    report_to: null